apiVersion: v1
kind: ConfigMap
metadata:
  name: centrifugo-config
data:
  config.json: |
    {
      "health": {
        "enabled": true
      },
      "engine": {
        "type": "redis",
        "redis": {
          "address": "{{ .Values.redis.host }}:{{ .Values.redis.port }}"
        }
      },
      "admin": {
        "insecure": true
      },
      "admin_web": {
        "enabled": true,
        "password": "{{ .Values.adminWeb.password | default "changeme" }}"
      },
      "http_api": {
        "insecure": true
      }
    }
