{{- if eq .Values.controller.type "rollout" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config-k6
  namespace: {{ .Release.Namespace }}
data:
  smoke.js: |-
{{ .Files.Get "files/k6s/smoke.js" | indent 4 }}
{{- end }}
