apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
#  annotations:
#    argocd.argoproj.io/sync-wave: "30"
#    argocd.argoproj.io/hook: PreSync  # Or Sync; runs before/after sync phase
#    argocd.argoproj.io/hook-weight: "-1"  # Negative: early in phase
#    argocd.argoproj.io/hook-delete-policy: HookSucceeded  # Clean up on success
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com
    privateKeySecretRef:
      name: letsencrypt-dns-account-key
    solvers:
      - selector:
          dnsZones:
            - "example.com"
        dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
      # Uncomment for multi-zone
      # - selector:
      #     dnsZones:
      #       - "example.org"
      #       - "example.net"
      #   dns01:
      #     cloudflare:
      #       apiTokenSecretRef:
      #         name: cloudflare-external-dns-token  # Or separate secret
      #         key: api-token