groups:

- name: systemd_exporter

  rules:
    - alert: SystemdServiceNotActive
      expr: systemd_unit_state{state="active"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Systemd service not active (instance {{ $labels.instance }})
        description: "systemd service not active\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
