apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    environment: prod
spec:
  project: platform
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 20.6.0  # Chart version (Redis 7.4.x)
      helm:
        releaseName: redis
        valueFiles:
          - $values/gitops/platform/redis/values.yaml
    - repoURL: https://github.com/tobrazo/devops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
