apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-cluster-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app: cert-manager
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
