apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-autoscaler
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: cluster-autoscaler
  podMetricsEndpoints:
    - port: metrics
      interval: 30s