---
- name: Configure Redis master
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: 0644

- name: Restart Redis service
  systemd:
    name: redis-server
    state: restarted
    enabled: yes
